theme: jekyll-theme-cayman

gems:
  - jekyll-seo-tag
  
description: The open source Supply Side Platform
author: André Schmer
publisher: ATG - ad-tech-group GmbH
version: "Actual OpenSSP Version is V0.2"
